Rebuild on a weekly basis, if needed

diff --git a/.github/workflows/reusable-build.yml b/.github/workflows/reusable-build.yml
--- a/.github/workflows/reusable-build.yml
+++ b/.github/workflows/reusable-build.yml
@@ -58,8 +58,32 @@ on:
         required: false
 
 jobs:
+  check-update:
+    name: Check for updates
+    if: github.event_name == 'schedule'
+    runs-on: ubuntu-latest
+    steps:
+      - name: Log in to registry
+        shell: bash
+        run: podman login ${{ inputs.registry }} -u ${{ inputs.registry_user }} -p ${{ secrets.REGISTRY_TOKEN }}
+
+      - name: Check update
+        shell: bash
+        run: |
+          # 'dnf check-update'
+          # exit codes:
+          #   0 - no updates
+          #   100 - updates available
+          #   125 - tag/platform not found
+          #   127 - command not found
+          res=0
+          podman run ${{ env.VARIANT }} --quiet --rm ${{ inputs.previous_image }} dnf check-update || res=$?
+          echo "res=${res}" >> "$GITHUB_ENV"
+          echo "Exit code: '$res'"
+
   build-image:
     name: Build image
+    if: ${{ github.event_name != 'schedule' || env.res != 0 }}
     uses: AlmaLinux/atomic-ci/.github/workflows/build-image.yml@v6
     with:
       containerfile: ${{ inputs.containerfile }}
@@ -93,6 +117,7 @@ jobs:
 
   test-image:
     name: Test image
+    if: ${{ github.event_name != 'schedule' || env.res != 0 }}
     runs-on: ubuntu-latest
     needs: build-image
     env:
@@ -115,7 +140,7 @@ jobs:
   promote-image:
     name: Promote image
     needs: [build-image, test-image]
-    if: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
+    if: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) && (github.event_name != 'schedule' || env.res != 0) }}
     uses: AlmaLinux/atomic-ci/.github/workflows/retag-image.yml@v6
     with:
       image: ${{ needs.build-image.outputs.image-ref }}@${{ needs.build-image.outputs.digest }}
